spring:
  application:
    name: sdlcs-tenant
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sdlcs_test}?currentSchema=${DB_SCHEMA:sdlcs_tenant}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  flyway:
    enabled: false
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    schemas: ${DB_SCHEMA:sdlcs_tenant}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sdlcs_test}
    locations: classpath:/db/migration
server:
  servlet:
    context-path: /
  port: ${APP_PORT:9494}
eureka:
  client:
    enabled: true

